import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {
  applyMigrations,
  openDatabase,
  SqliteAuditRepository,
} from '@orc/db';
import { SqliteModelfileRepository } from '@orc/db/modelfiles';
import { AuditService } from '../dist/audit.js';
import {
  ModelfileLibraryError,
  ModelfileLibraryService,
} from '../dist/modelfile-library.js';

const NOW = new Date('2026-08-09T07:00:00.000Z');
const MODEL_DIGEST = 'b'.repeat(64);

function fixture(modelDetailOverride = {}) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'orc-modelfile-service-'));
  const database = openDatabase(path.join(directory, 'service.sqlite'));
  applyMigrations(database);
  database.prepare(`
    INSERT INTO users(id, username, password_hash, role, created_at)
    VALUES (?, ?, ?, 'admin', ?)
  `).run('user-1', 'admin', 'hash', NOW.toISOString());
  const repository = new SqliteModelfileRepository(database);
  const audit = new AuditService(new SqliteAuditRepository(database), () => NOW);
  const detail = {
    targetId: 'target-observed',
    transport: { mode: 'published-binding' },
    identity: {
      name: 'hf.co/example/model:Q4_K_M',
      model: 'hf.co/example/model:Q4_K_M',
      digest: MODEL_DIGEST,
      modifiedAt: NOW.toISOString(),
    },
    details: {
      format: 'gguf', family: 'qwen3', families: ['qwen3'], parameterSize: '9B',
      quantizationLevel: 'Q4_K_M', parentModel: null,
    },
    capabilities: ['completion'],
    modelfile: '# generated by Ollama\nFROM /root/.ollama/models/blobs/sha256:abc\nPARAMETER num_ctx 32768\n',
    parameters: 'num_ctx 32768', template: '{{ .Prompt }}', system: null, license: null, requires: null,
    architecture: {
      architecture: 'qwen3', parameterCount: 9000000000, contextLength: 32768,
      embeddingLength: 4096, blockCount: 36, quantizationVersion: 2,
    },
    provenancePreview: {
      from: { reference: '/root/.ollama/models/blobs/sha256:abc', kind: 'local-artifact' },
      adapters: [],
    },
    ...modelDetailOverride,
  };
  const calls = [];
  const modelDetails = {
    async read(targetId, requestedModel) {
      calls.push({ targetId, requestedModel });
      return detail;
    },
  };
  return {
    database,
    repository,
    calls,
    service: new ModelfileLibraryService(repository, audit, modelDetails, () => NOW),
  };
}

function auditRows(database) {
  return database.prepare(`
    SELECT action, parameters_redacted_json, target_id, result
    FROM audit_events ORDER BY timestamp, id
  `).all();
}

test('manual creation preserves exact raw source and audits only identifiers and hash', () => {
  const { database, service } = fixture();
  try {
    const rawText = '# keep spacing\r\nFROM llama3.2:latest\r\nPARAMETER temperature 0.7\r\n';
    const created = service.createManual('user-1', {
      displayName: '  Local llama  ',
      description: '  Draft  ',
      rawText,
    });
    assert.equal(created.displayName, 'Local llama');
    assert.equal(created.description, 'Draft');
    assert.equal(created.currentRevision.revisionNumber, 1);
    assert.equal(created.currentRevision.sourceKind, 'manual');
    assert.equal(created.currentRevision.rawText, rawText);
    assert.equal(created.currentRevision.importedDigest, null);
    assert.deepEqual(service.list(), [{
      id: created.id,
      displayName: created.displayName,
      description: created.description,
      currentRevisionId: created.currentRevisionId,
      currentRevisionNumber: 1,
      currentSourceKind: 'manual',
      createdAt: NOW.toISOString(),
      updatedAt: NOW.toISOString(),
    }]);
    assert.deepEqual(service.listRevisions(created.id), [{
      id: created.currentRevision.id,
      revisionNumber: 1,
      parentRevisionId: null,
      contentSha256: created.currentRevision.contentSha256,
      sourceKind: 'manual',
      importedTargetId: null,
      importedModel: null,
      importedDigest: null,
      createdAt: NOW.toISOString(),
    }]);
    assert.equal(service.read(created.id).currentRevision.rawText, rawText);
    assert.equal(service.readRevision(created.id, created.currentRevision.id).rawText, rawText);

    const audits = auditRows(database);
    assert.equal(audits.length, 1);
    assert.equal(audits[0].action, 'modelfile.create');
    assert.equal(audits[0].result, 'succeeded');
    assert.equal(audits[0].parameters_redacted_json.includes(rawText), false);
    assert.equal(audits[0].parameters_redacted_json.includes(created.currentRevision.contentSha256), true);
  } finally {
    database.close();
  }
});

test('new revision requires the exact current base and leaves old raw source immutable', () => {
  const { database, service } = fixture();
  try {
    const first = service.createManual('user-1', {
      displayName: 'Versioned',
      rawText: 'FROM first:latest\n',
    });
    const secondText = '# second\nFROM second:latest\n';
    const second = service.append('user-1', first.id, {
      expectedCurrentRevisionId: first.currentRevisionId,
      rawText: secondText,
    });
    assert.equal(second.currentRevision.revisionNumber, 2);
    assert.equal(second.currentRevision.parentRevisionId, first.currentRevisionId);
    assert.equal(second.currentRevision.rawText, secondText);
    assert.equal(service.readRevision(first.id, first.currentRevisionId).rawText, 'FROM first:latest\n');

    assert.throws(
      () => service.append('user-1', first.id, {
        expectedCurrentRevisionId: first.currentRevisionId,
        rawText: 'FROM stale:latest\n',
      }),
      (error) => error instanceof ModelfileLibraryError
        && error.code === 'MODEFILE_REVISION_CONFLICT'
        && error.statusCode === 409,
    );
    assert.equal(service.listRevisions(first.id).length, 2);
  } finally {
    database.close();
  }
});

test('installed-model import persists only server-observed Modelfile identity and digest', async () => {
  const { database, service, calls } = fixture();
  try {
    const imported = await service.importInstalled('user-1', {
      targetId: 'target-requested',
      model: 'hf.co/example/model:Q4_K_M',
      description: 'Imported baseline',
    });
    assert.deepEqual(calls, [{
      targetId: 'target-requested',
      requestedModel: 'hf.co/example/model:Q4_K_M',
    }]);
    assert.equal(imported.displayName, 'hf.co/example/model:Q4_K_M');
    assert.equal(imported.currentRevision.sourceKind, 'installed-model-import');
    assert.equal(imported.currentRevision.importedTargetId, 'target-observed');
    assert.equal(imported.currentRevision.importedModel, 'hf.co/example/model:Q4_K_M');
    assert.equal(imported.currentRevision.importedDigest, MODEL_DIGEST);
    assert.equal(imported.currentRevision.rawText.startsWith('# generated by Ollama'), true);

    const audits = auditRows(database);
    assert.equal(audits.length, 1);
    assert.equal(audits[0].action, 'modelfile.import-installed');
    assert.equal(audits[0].target_id, 'target-observed');
    assert.equal(audits[0].parameters_redacted_json.includes(imported.currentRevision.rawText), false);
    assert.equal(audits[0].parameters_redacted_json.includes(MODEL_DIGEST), true);
  } finally {
    database.close();
  }
});

test('invalid or oversized raw source fails before persistence and import requires generated Modelfile', async () => {
  const { database, service } = fixture({ modelfile: null });
  try {
    assert.throws(
      () => service.createManual('user-1', { displayName: 'Bad', rawText: 'x\u0000y' }),
      (error) => error instanceof ModelfileLibraryError && error.code === 'INVALID_MODEFILE_TEXT',
    );
    assert.equal(service.list().length, 0);

    await assert.rejects(
      () => service.importInstalled('user-1', { targetId: 'target', model: 'model:latest' }),
      (error) => error instanceof ModelfileLibraryError
        && error.code === 'MODEFILE_IMPORT_UNAVAILABLE'
        && error.statusCode === 409,
    );
    assert.equal(service.list().length, 0);
    assert.equal(auditRows(database).length, 0);
  } finally {
    database.close();
  }
});
