import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {
  applyMigrations,
  openDatabase,
  SqliteHostOnboardingRepository,
  SqliteOllamaTargetRepository,
  SqliteSshCredentialRepository,
} from '@orc/db';
import { HostOnboardingService } from '../dist/hosts.js';
import {
  OllamaModelDetailError,
  OllamaModelDetailService,
  parseModelfileProvenancePreview,
  parseOllamaShowResponse,
  validateRequestedModelName,
} from '../dist/ollama-model-details.js';

const SSH_HOST = process.env.SSH_HOST;
const SSH_PORT = Number(process.env.SSH_PORT ?? '2222');
const SSH_USER = process.env.SSH_USER;
const SSH_PRIVATE_KEY_PATH = process.env.SSH_PRIVATE_KEY_PATH;
const DOCKER_FIXTURE_LOG = process.env.ORC_DOCKER_FIXTURE_LOG;
const CONTAINER_STATE = process.env.ORC_CONTAINER_STATE;
const HAS_FIXTURE = Boolean(SSH_HOST && SSH_USER && SSH_PRIVATE_KEY_PATH && DOCKER_FIXTURE_LOG && CONTAINER_STATE);
const MASTER_KEY = Buffer.alloc(32, 0x76);
const NOW = '2026-08-09T06:15:00.000Z';
const DIGEST = 'c'.repeat(64);

const installed = {
  name: 'model-a:latest',
  model: 'model-a:latest',
  modifiedAt: '2026-08-09T05:00:00.000Z',
  sizeBytes: 123456789,
  digest: DIGEST,
  details: {
    format: 'gguf',
    family: 'qwen3',
    families: ['qwen3'],
    parameterSize: '9.0B',
    quantizationLevel: 'Q4_K_XL',
  },
};

function tagsPayload() {
  return {
    models: [{
      name: installed.name,
      model: installed.model,
      modified_at: installed.modifiedAt,
      size: installed.sizeBytes,
      digest: installed.digest,
      details: {
        format: installed.details.format,
        family: installed.details.family,
        families: installed.details.families,
        parameter_size: installed.details.parameterSize,
        quantization_level: installed.details.quantizationLevel,
      },
    }],
  };
}

function showPayload() {
  return {
    modelfile: [
      '# Modelfile generated by "ollama show"',
      '# FROM model-a:latest',
      'FROM /root/.ollama/models/blobs/sha256:deadbeef',
      'ADAPTER hf.co/example/adapter:latest',
      'PARAMETER num_ctx 32768',
    ].join('\n'),
    parameters: 'num_ctx 32768\ntemperature 0.7',
    template: '{{ .System }}\n{{ .Prompt }}',
    system: 'You are a bounded test model.',
    license: 'Test license text',
    requires: 'ollama >= 0.12',
    details: { parent_model: 'model-base:latest', secret_detail: 'DO-NOT-RETURN' },
    capabilities: ['completion', 'tools'],
    model_info: {
      'general.architecture': 'qwen3',
      'general.parameter_count': 9000000000,
      'general.quantization_version': 2,
      'qwen3.context_length': 32768,
      'qwen3.embedding_length': 4096,
      'qwen3.block_count': 36,
      'tokenizer.ggml.tokens': ['DO-NOT-RETURN'],
    },
    tensors: [{ name: 'DO-NOT-RETURN' }],
    remote_host: 'DO-NOT-RETURN',
    unknown: 'DO-NOT-RETURN',
  };
}

function resetFixture() {
  if (!HAS_FIXTURE) return;
  fs.writeFileSync(DOCKER_FIXTURE_LOG, '');
  fs.writeFileSync(CONTAINER_STATE, 'running');
  fs.writeFileSync('/tmp/orc-status-fixture-mode', 'normal');
}

async function detailService() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'orc-ollama-detail-'));
  const database = openDatabase(path.join(directory, 'details.sqlite'));
  applyMigrations(database);
  const hosts = new SqliteHostOnboardingRepository(database);
  const credentials = new SqliteSshCredentialRepository(database);
  const targets = new SqliteOllamaTargetRepository(database);
  const onboarding = new HostOnboardingService(hosts, MASTER_KEY, () => new Date(NOW));
  const probe = await onboarding.probe({ hostname: SSH_HOST, port: SSH_PORT });
  const created = await onboarding.create({
    displayName: 'Detail fixture host', hostname: SSH_HOST, port: SSH_PORT, username: SSH_USER,
    confirmedFingerprint: probe.fingerprint, privateKey: fs.readFileSync(SSH_PRIVATE_KEY_PATH, 'utf8'),
  });
  targets.saveSelection({
    id: 'target-details', hostId: created.id, displayName: 'Detail Ollama',
    selectedContainerId: 'ollama-container-id', containerNameOverride: null, enabled: true,
    createdAt: NOW, updatedAt: NOW,
  });
  return {
    database,
    service: new OllamaModelDetailService(hosts, credentials, targets, MASTER_KEY),
  };
}

async function listenModelServer(handler) {
  const server = http.createServer(handler);
  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(11434, '127.0.0.1', resolve);
  });
  return server;
}

async function closeServer(server) {
  await new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
}

async function readJsonRequest(request) {
  const chunks = [];
  for await (const chunk of request) chunks.push(Buffer.from(chunk));
  return JSON.parse(Buffer.concat(chunks).toString('utf8'));
}

test('show parser returns only bounded explicit detail fields and conservative provenance preview', () => {
  const parsed = parseOllamaShowResponse(Buffer.from(JSON.stringify(showPayload())), installed);
  assert.equal(parsed.format, 'gguf');
  assert.equal(parsed.parentModel, 'model-base:latest');
  assert.deepEqual(parsed.capabilities, ['completion', 'tools']);
  assert.deepEqual(parsed.architecture, {
    architecture: 'qwen3', parameterCount: 9000000000, contextLength: 32768,
    embeddingLength: 4096, blockCount: 36, quantizationVersion: 2,
  });
  assert.deepEqual(parsed.provenancePreview, {
    from: { reference: '/root/.ollama/models/blobs/sha256:deadbeef', kind: 'local-artifact' },
    adapters: [{ reference: 'hf.co/example/adapter:latest', kind: 'model-reference' }],
  });
  assert.equal(JSON.stringify(parsed).includes('DO-NOT-RETURN'), false);
});

test('Modelfile preview ignores comments and does not invent lineage for local artifacts', () => {
  assert.deepEqual(parseModelfileProvenancePreview([
    '# FROM should-not-win:latest',
    'FROM llama3.2:latest',
    'ADAPTER ./adapter',
  ].join('\n')), {
    from: { reference: 'llama3.2:latest', kind: 'model-reference' },
    adapters: [{ reference: './adapter', kind: 'local-artifact' }],
  });
});

test('detail parser and requested model boundary reject invalid or oversized input', () => {
  for (const value of ['', 'bad model', 'bad\r\nmodel', `m${'x'.repeat(512)}`]) {
    assert.throws(
      () => validateRequestedModelName(value),
      (error) => error instanceof OllamaModelDetailError && error.code === 'INVALID_MODEL_NAME',
    );
  }
  const tooManyCapabilities = showPayload();
  tooManyCapabilities.capabilities = Array.from({ length: 33 }, (_, index) => `cap-${index}`);
  assert.throws(
    () => parseOllamaShowResponse(Buffer.from(JSON.stringify(tooManyCapabilities)), installed),
    (error) => error instanceof OllamaModelDetailError && error.code === 'OLLAMA_MODEL_DETAIL_INVALID',
  );
  const hugeModelfile = showPayload();
  hugeModelfile.modelfile = 'x'.repeat(512 * 1024 + 1);
  assert.throws(
    () => parseOllamaShowResponse(Buffer.from(JSON.stringify(hugeModelfile)), installed),
    (error) => error instanceof OllamaModelDetailError && error.code === 'OLLAMA_MODEL_DETAIL_INVALID',
  );
});

test('real OpenSSH detail flow checks tags membership then posts exact bounded show request', { skip: !HAS_FIXTURE }, async () => {
  resetFixture();
  const requests = [];
  const server = await listenModelServer(async (request, response) => {
    response.setHeader('content-type', 'application/json');
    if (request.method === 'GET' && request.url === '/api/tags') {
      requests.push({ method: request.method, url: request.url, body: null });
      response.end(JSON.stringify(tagsPayload()));
      return;
    }
    if (request.method === 'POST' && request.url === '/api/show') {
      const body = await readJsonRequest(request);
      requests.push({ method: request.method, url: request.url, body });
      response.end(JSON.stringify(showPayload()));
      return;
    }
    response.statusCode = 404;
    response.end('{}');
  });
  const { database, service } = await detailService();
  try {
    fs.writeFileSync(DOCKER_FIXTURE_LOG, '');
    const result = await service.read('target-details', 'model-a:latest');
    assert.equal(result.identity.digest, DIGEST);
    assert.equal(result.details.parentModel, 'model-base:latest');
    assert.equal(result.modelfile.includes('PARAMETER num_ctx'), true);
    assert.deepEqual(requests, [
      { method: 'GET', url: '/api/tags', body: null },
      { method: 'POST', url: '/api/show', body: { model: 'model-a:latest', verbose: false } },
    ]);
    assert.deepEqual(fs.readFileSync(DOCKER_FIXTURE_LOG, 'utf8').trim().split(/\r?\n/u).filter(Boolean), [
      'inspect ollama-container-id',
    ]);
  } finally {
    database.close();
    await closeServer(server);
    resetFixture();
  }
});

test('model absent from fresh inventory fails before show request', { skip: !HAS_FIXTURE }, async () => {
  resetFixture();
  let showCalls = 0;
  const server = await listenModelServer(async (request, response) => {
    response.setHeader('content-type', 'application/json');
    if (request.method === 'GET' && request.url === '/api/tags') {
      response.end(JSON.stringify(tagsPayload()));
      return;
    }
    if (request.method === 'POST' && request.url === '/api/show') showCalls += 1;
    response.statusCode = 404;
    response.end('{}');
  });
  const { database, service } = await detailService();
  try {
    await assert.rejects(
      () => service.read('target-details', 'not-installed:latest'),
      (error) => error instanceof OllamaModelDetailError && error.code === 'MODEL_NOT_FOUND' && error.statusCode === 404,
    );
    assert.equal(showCalls, 0);
  } finally {
    database.close();
    await closeServer(server);
    resetFixture();
  }
});

test('show HTTP errors fail safely without leaking remote response bodies', { skip: !HAS_FIXTURE }, async () => {
  resetFixture();
  const server = await listenModelServer(async (request, response) => {
    if (request.method === 'GET' && request.url === '/api/tags') {
      response.end(JSON.stringify(tagsPayload()));
      return;
    }
    if (request.method === 'POST' && request.url === '/api/show') {
      await readJsonRequest(request);
      response.statusCode = 503;
      response.end('SECRET-SHOW-BODY');
      return;
    }
    response.statusCode = 404;
    response.end('{}');
  });
  const { database, service } = await detailService();
  try {
    await assert.rejects(
      () => service.read('target-details', 'model-a:latest'),
      (error) => {
        assert(error instanceof OllamaModelDetailError);
        assert.equal(error.message.includes('SECRET-SHOW-BODY'), false);
        return true;
      },
    );
  } finally {
    database.close();
    await closeServer(server);
    resetFixture();
  }
});
